tasks:
  - init: conda env create -f travel-planner-agent-demo/environment.yml && conda activate travel-agent-demo
  - command: conda activate travel-agent-demo && streamlit run travel-planner-agent-demo/agents/travel_planner_visualizer.py
ports:
  - port: 8501
    onOpen: open-preview